server:
  port: 8080

spring:
  webflux:
    base-path: /api
  main:
    allow-bean-definition-overriding: true

openai:
  api-key: ""
  api-url: https://api.openai.com/v1/completions

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG



