server:
  port: 8080

spring:
#  webflux:
#    base-path: /api
  main:
    allow-bean-definition-overriding: true

openai:
  api-key: ""
  api-url: https://api.openai.com/v1

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.web.reactive.function.client.WebClient: DEBUG

resilience4j:
  retry:
    instances:
      openai-api:
        max-attempts: 3
        wait-duration: 1000ms
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
        ignore-exceptions:
          - java.net.ConnectException

